spring.datasource.url=jdbc:postgresql://localhost:5433/dormitory_db
spring.datasource.username=postgres
spring.datasource.password=0520

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.enabled=false
server.address=0.0.0.0
server.port=8080

gemini.api.key=AIzaSyD5gVwTnGdsIsjePfHeehrDzQ01PGXXNJM
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent