spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/dormitory_db
spring.datasource.username=aizhan
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false

server.port=8080